# 本服务基础信息配置
server:
  port: 1573

# 日志配置
logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: INFO
    org.apache.coyote.http11.Http11OutputBuffer: INFO
# 安全认证服务配置
security:
  user:
    name: signit-prod
    password: signit-prod-password

# eureka客户端信息配置
eureka:
   instance:
     hostname: mss-user.ns.me
     instance-id: ${random.uuid}(${spring.application.name}::${eureka.instance.hostname}:${server.port})
   client:
     registry-fetch-interval-seconds: 5
     service-url: 
       defaultZone: http://${security.user.name}:${security.user.password}@mss-eureka01.ns.me:5683/eureka/,http://${security.user.name}:${security.user.password}@mss-eureka02.ns.me:5683/eureka/,http://${security.user.name}:${security.user.password}@mss-eureka03.ns.me:5683/eureka/
       
test: 
  prop: I'm from GIT-prod-1.0